=== mohanarcoinfoindia/DomaWebPortal/Sites/xsd/gridtoolbar.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Toolbar">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="Item" />
        </xs:choice>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="Group" />
        </xs:choice>               
      </xs:sequence>
      <xs:attribute name="enabled" type="xs:boolean" />
      <xs:attribute name="fullwidth" type="xs:boolean" />
      <xs:attribute name="disablefixedbuttons" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="Item">
    <xs:complexType>
      <xs:attribute name="Text" type="xs:string" />
      <xs:attribute name="LabelE" type="xs:string" />
      <xs:attribute name="LabelN" type="xs:string" />
      <xs:attribute name="LabelF" type="xs:string" />
      <xs:attribute name="LabelG" type="xs:string" />
      <xs:attribute name="ImageUrl" type="xs:string" />
      <xs:attribute name="NavigateUrl" type="xs:string" />
       <xs:attribute name="Endpoint" type="xs:string" />
      <xs:attribute name="ToggleOnMultiSelect" type="xs:boolean" />
      <xs:attribute name="ToggleOnCaseMultiSelect" type="xs:boolean"/>
      <xs:attribute name="ToggleOnMailMultiSelect" type="xs:boolean"/>
      <xs:attribute name="isSeparator" type="xs:boolean" />
      <xs:attribute name="ShowText" type="xs:boolean" />
      <xs:attribute name="isCustomActionPlaceHolder" type="xs:boolean" />
      <xs:attribute name="RequiredFolderAcl" type="xs:int"/>
      <xs:attribute name="Roles" type="xs:string"/>
      <xs:attribute name="visible" type="xs:boolean" />
     <xs:attribute name="siteVersion" type="xs:int" />
     <xs:attribute name="isPrimary" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="Group" msdata:IsDataSet="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Item" />
      </xs:choice>
      <xs:attribute name="Text" type="xs:string" />
      <xs:attribute name="LabelE" type="xs:string" />
      <xs:attribute name="LabelN" type="xs:string" />
      <xs:attribute name="LabelF" type="xs:string" />
      <xs:attribute name="LabelG" type="xs:string" />
      <xs:attribute name="ImageUrl" type="xs:string" />
      <xs:attribute name="ShowText" type="xs:boolean" />
      <xs:attribute name="RequiredFolderAcl" type="xs:int"/>
      <xs:attribute name="Roles" type="xs:string"/>
      <xs:attribute name="visible" type="xs:boolean" />
    </xs:complexType>

  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Toolbar" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/DefaultGridToolbar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">

  <Item Text="Show Sidepanel" LabelN="Zijpaneel tonen" LabelF="Montrer le panneau latéral" ImageClass="icon-chevron-expand icon-color-light" NavigateUrl="javascript:#GRID#.ToggleShowSideBar();"/> 
  <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraîchir" NavigateUrl="javascript:#GRID#.Reload();"/>
  <Item Text="What's new" ImageClass="icon-folder-mynewdocs" ShowText="false" LabelE="" LabelF="Quoi de neuf" LabelN="Nieuwe items" LabelG="Neuigkeiten" NavigateUrl="javascript:#GRID#.ToggleWhatsNew();"/>
  <Item isSeparator="true"/>
  <Item Text="Add" LabelE="Add" LabelN="Toevoegen" LabelF="Ajouter" LabelG="Add" ImageClass="icon-add-new" NavigateUrl="javascript:#GRID#.AddNew();" visible="false"/>
  <Item isSeparator="true" visible="false"/>
  
  <Item Text="Check Out" LabelF="Réserver" LabelN="Uitchecken" ToggleOnMultiSelect="true" ImageClass="icon-document-CHout" NavigateUrl="javascript:#GRID#.DoDocumentListAction(7,0);"/>
  <Item Text="Check In" LabelF="Enregistrer" LabelN="Inchecken" ToggleOnMultiSelect="true" ImageClass="icon-document-CHin" NavigateUrl="javascript:#GRID#.DoDocumentListAction(9,0);"/>
  <Item Text="Cancel Check out" LabelF="Annuler la réservation" LabelN="Uitchecken annuleren" ToggleOnMultiSelect="true" ImageClass="icon-document-CHout-cancel" NavigateUrl="javascript:#GRID#.DoDocumentListAction(8,0);"/>

  <Item isSeparator="true"/>

 <Item Text="Start workflow" visible="false" LabelE="Start workflow" LabelN="Workflow starten" LabelF="Démarrer workflow" ImageClass="icon-case" ToggleOnMultiSelect="true" NavigateUrl="javascript:#GRID#.StartProcedureFromSelection();"/>
  <Item Text="Create Object" visible="false" LabelE="Create Object" LabelN="Object aanmaken" LabelF="Créer objet" ImageClass="icon-add-new" ToggleOnMultiSelect="true" NavigateUrl="javascript:#GRID#.CreateObjectFromSelection();"/> 
  <Item isSeparator="true" visible="false"></Item>
  
  <Item Text="Print" LabelE="Print" LabelN="Afdrukken" LabelF="Imprimer" LabelG="Abdrucken" ImageClass="icon-printer"  NavigateUrl="javascript:#GRID#.PrintGrid();"/>
  <Item Text="Export to Excel" LabelE="Export to Excel" LabelN="Exporteren naar Excel" LabelF="Exporter vers Excel" LabelG="Export to Excel" ImageClass="icon-filetype-excel" NavigateUrl="javascript:#GRID#.PrintGridToExcel('auto');"/>

  <Item Text="Send by mail" ToggleOnMultiSelect="true" ImageClass="icon-message-mail-attach"  LabelE="Send by e-mail" LabelN="Versturen per mail" LabelF="Envoyer par courriel" LabelG="" NavigateUrl="javascript:#GRID#.MailSelection();" />
  <Item Text="Download files to ZIP" ToggleOnMultiSelect="true" LabelE="" LabelN="Bestanden downloaden naar ZIP" LabelF="Télécharger les fichiers en ZIP" LabelG="" ImageClass="icon-download-zip" NavigateUrl="javascript:#GRID#.DoDocumentListAction(2,-1);"/>
  <Item Text="Download to PDF" ToggleOnMultiSelect="true" LabelE="" LabelN="Downloaden naar PDF" LabelF="Télécharger en PDF" LabelG="" ImageClass="icon-filetype-pdf" NavigateUrl="javascript:#GRID#.DoDocumentListAction(6,-1);"/>

  <Item Text="Compare Documents" ToggleOnMultiSelect="true" ImageClass="icon-document-compare" ShowText="false"  LabelE="" LabelN="Documenten vergelijken" LabelF="Comparer les documents" LabelG="" NavigateUrl="Javascript:PC().OpenWindow('./Tools/DocCompare.aspx?docs=' + #GRID#.GetSelection(),'compdocs');" />
  <Item Text="Compare Files" ToggleOnMultiSelect="true" ImageClass="icon-file-compare" ShowText="false" LabelE="" LabelN="Bestanden vergelijken" LabelF="Comparer les fichiers" LabelG="" NavigateUrl="Javascript:PC().OpenWindow('./Tools/FileCompare.aspx?docs=' + #GRID#.GetSelection(),'compfiles');" />
  <Item isCustomActionPlaceHolder="true"></Item>
  <Item isSeparator="true"></Item>
  <Item Text="Copy/Move to Folder" ToggleOnMultiSelect="true"  LabelE="Copy/Move/Shortcut to folder" ImageClass="icon-folder-moveto" LabelN="Kopieren/Verplaatsen/Snelkoppeling naar map" LabelF="Copier/Deplacer/Raccourci vers..." LabelG=""  NavigateUrl="javascript:#GRID#.CopyMoveSelection();" />
  <Item Text="Delete" ToggleOnMultiSelect="true" LabelE="Delete" LabelN="Verwijderen" LabelF="Supprimer" LabelG="Löschen" ImageClass="icon-delete" NavigateUrl="javascript:#GRID#.DoDocumentListAction(4,0);"/>
  <Item isSeparator="true"></Item>
  <Item Text="Add to Clipboard" ToggleOnMultiSelect="true" ImageClass="icon-copy-clipboard"  LabelE="Add to Docroom Clipboard" LabelN="Toevoegen aan het DocRoom Klembord" LabelF="Ajouter au Clipboard" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(7);" />
  <Item Text="Add to favorites" ToggleOnMultiSelect="true" ImageClass="icon-favorites-add"  LabelE="Add to favorites" LabelN="Toevoegen aan favorieten" LabelF="Ajouter aux favoris" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(3);" />
  <Item Text="Add to basket" ToggleOnMultiSelect="true" ImageClass="icon-basket-add"  LabelE="Add to basket" LabelN="Toevoegen aan mand" LabelF="Ajouter au panier" LabelG="In den Korb legen" NavigateUrl="Javascript:#GRID#.AddToSelection(2);" />  
</Toolbar>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/BasketGridToolbar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">
  <Item Text="Clear Basket" LabelN="Mand leegmaken" LabelF="Vider le panier" ImageClass="icon-basket-remove-all" NavigateUrl="javascript:#GRID#.ClearSelection(2,true);" />
  <Item Text="Remove from Basket" ToggleOnMultiSelect="true" LabelN="Verwijderen uit de mand" LabelF="Supprimer du panier" ImageClass="icon-basket-remove" NavigateUrl="javascript:#GRID#.RemoveFromSelection(2,true);" />
  <Item isSeparator="true"></Item>
  <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraïchir" NavigateUrl="javascript:#GRID#.Reload();"/>
  <Item Text="What's new" ImageClass="icon-folder-mynewdocs" ShowText="false" LabelE="" LabelF="Quoi de neuf" LabelN="Nieuwe items" LabelG="Neuigkeiten" NavigateUrl="javascript:#GRID#.ToggleWhatsNew();"/>
  <Item isSeparator="true"></Item>
  <Item Text="Print" LabelE="Print" LabelN="Afdrukken" LabelF="Imprimer" LabelG="Abdrucken" ImageClass="icon-printer"  NavigateUrl="javascript:#GRID#.PrintGrid();"/>
  <Item Text="Send by mail" ToggleOnMultiSelect="true" ImageClass="icon-message-mail-attach"  LabelE="Send by e-mail" LabelN="Versturen per mail" LabelF="Envoyer par courriel" LabelG="" NavigateUrl="javascript:#GRID#.MailSelection();" />
  <Item Text="Download files to ZIP" ToggleOnMultiSelect="true" LabelE="" LabelN="Bestanden downloaden naar ZIP" LabelF="Télécharger les fichiers en ZIP" LabelG="" ImageClass="icon-download-zip" NavigateUrl="javascript:#GRID#.DoDocumentListAction(2,0);"/>
  <Item Text="Compare Documents" ToggleOnMultiSelect="true" ImageClass="icon-document-compare" ShowText="false"  LabelE="" LabelN="Documenten vergelijken" LabelF="Comparer les documents" LabelG="" NavigateUrl="Javascript:PageController().OpenWindow('./Tools/DocCompare.aspx?docs=' + #GRID#.GetSelection(),'compdocs');" />
  <Item Text="Compare Files" ToggleOnMultiSelect="true" ImageClass="icon-file-compare" ShowText="false" LabelE="" LabelN="Bestanden vergelijken" LabelF="Comparer les fichiers" LabelG="" NavigateUrl="Javascript:PageController().OpenWindow('./Tools/FileCompare.aspx?docs=' + #GRID#.GetSelection(),'compfiles');" />
  <Item isCustomActionPlaceHolder="true"></Item>
  <Item isSeparator="true"></Item>
  <Item Text="Copy/Move to Folder" ToggleOnMultiSelect="true"  LabelE="Copy/Move/Shortcut to folder" ImageClass="icon-folder-moveto" LabelN="Kopieren/Verplaatsen/Snelkoppeling naar map" LabelF="Copier/Deplacer/Raccourci vers..." LabelG=""  NavigateUrl="javascript:#GRID#.CopyMoveSelection();" />
  <Item Text="Delete" ToggleOnMultiSelect="true" LabelE="Delete" LabelN="Verwijderen" LabelF="Supprimer" LabelG="Löschen" ImageClass="icon-delete" NavigateUrl="javascript:#GRID#.DoDocumentListAction(4,0);"/>
  <Item isSeparator="true"></Item>
  <Item Text="Add to Clipboard" ToggleOnMultiSelect="true" ImageClass="icon-copy-clipboard"  LabelE="Add to Docroom Clipboard" LabelN="Toevoegen aan het DocRoom Klembord" LabelF="Ajouter au Clipboard" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(7);" />
  <Item Text="Add to favorites" ToggleOnMultiSelect="true" ImageClass="icon-favorites-add"  LabelE="Add to your favorites" LabelN="Toevoegen aan favorieten" LabelF="Ajouter aux favoris" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(3);" />

</Toolbar>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/MyCheckedOutDocsGridToolbar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">
  <Item Text="Show Sidepanel" LabelN="Zijpaneel tonen" LabelF="Montrer le panneau latéral" ImageClass="icon-chevron-expand icon-color-light" NavigateUrl="javascript:#GRID#.ToggleShowSideBar();"/>
  <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraïchir" NavigateUrl="javascript:#GRID#.Reload();"/>
  <Item isSeparator="true"/>

  <Item Text="Check In" LabelF="Enregistrer" LabelN="Inchecken" ToggleOnMultiSelect="true" ImageClass="icon-document-CHin" NavigateUrl="javascript:#GRID#.DoDocumentListAction(9,0);"/>
  <Item Text="Cancel Check out" LabelF="Annuler la réservation" LabelN="Uitchecken annuleren" ToggleOnMultiSelect="true" ImageClass="icon-document-CHout-cancel" NavigateUrl="javascript:#GRID#.DoDocumentListAction(8,0);"/>

  <Item isSeparator="true"></Item>
  <Item Text="Print" LabelE="Print" LabelN="Afdrukken" LabelF="Imprimer" LabelG="Abdrucken" ImageClass="icon-printer"  NavigateUrl="javascript:#GRID#.PrintGrid();"/>
  <Item Text="Export to Excel" LabelE="Export to Excel" LabelN="Exporteren naar Excel" LabelF="Exporter vers Excel" LabelG="Export to Excel" ImageClass="icon-filetype-excel"  NavigateUrl="javascript:#GRID#.PrintGridToExcel('auto');"/>

  <Item Text="Send by mail" ToggleOnMultiSelect="true" ImageClass="icon-message-mail-attach"  LabelE="Send by e-mail" LabelN="Versturen per mail" LabelF="Envoyer par courriel" LabelG="" NavigateUrl="javascript:#GRID#.MailSelection(4048567);" />
  <Item Text="Download files to ZIP" ToggleOnMultiSelect="true" LabelE="" LabelN="Bestanden downloaden naar ZIP" LabelF="Télécharger les fichiers en ZIP" LabelG="" ImageClass="icon-download-zip" NavigateUrl="javascript:#GRID#.DoDocumentListAction(2,0);"/>
  <Item Text="Download to PDF" ToggleOnMultiSelect="true" LabelE="" LabelN="Downloaden naar PDF" LabelF="Télécharger en PDF" LabelG="" ImageClass="icon-filetype-pdf" NavigateUrl="javascript:#GRID#.DoDocumentListAction(6,0);"/>

  <Item Text="Compare Documents" ToggleOnMultiSelect="true" ImageClass="icon-document-compare" ShowText="false"  LabelE="" LabelN="Documenten vergelijken" LabelF="Comparer les documents" LabelG="" NavigateUrl="Javascript:PC().OpenWindow('./Tools/DocCompare.aspx?docs=' + #GRID#.GetSelection(),'compdocs');" />
  <Item Text="Compare Files" ToggleOnMultiSelect="true" ImageClass="icon-file-compare" ShowText="false" LabelE="" LabelN="Bestanden vergelijken" LabelF="Comparer les fichiers" LabelG="" NavigateUrl="Javascript:PC().OpenWindow('./Tools/FileCompare.aspx?docs=' + #GRID#.GetSelection(),'compfiles');" />
  <Item isCustomActionPlaceHolder="true"></Item>
  <Item isSeparator="true"></Item>
  <Item Text="Copy/Move to Folder" ToggleOnMultiSelect="true"  LabelE="Copy/Move/Shortcut to folder" ImageClass="icon-folder-moveto" LabelN="Kopieren/Verplaatsen/Snelkoppeling naar map" LabelF="Copier/Deplacer/Raccourci vers..." LabelG=""  NavigateUrl="javascript:#GRID#.CopyMoveSelection();" />
  <Item Text="Delete" ToggleOnMultiSelect="true" LabelE="Delete" LabelN="Verwijderen" LabelF="Supprimer" LabelG="Löschen" ImageClass="icon-delete" NavigateUrl="javascript:#GRID#.DoDocumentListAction(4,0);"/>
 
</Toolbar>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/mailInboxToolbar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">
<Item Text="Show Sidepanel" LabelN="Zijpaneel tonen" LabelF="Montrer le panneau latéral" ImageClass="icon-chevron-expand icon-color-light" NavigateUrl="javascript:#GRID#.ToggleShowSideBar();"/>
  <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraîchir" NavigateUrl="javascript:#GRID#.Reload();"/>

  <Item Text="What's new" ImageClass="icon-folder-mynewdocs" ShowText="false" LabelE="" LabelF="Quoi de neuf" LabelN="Nieuwe items" LabelG="Neuigkeiten" NavigateUrl="javascript:#GRID#.ToggleWhatsNew();"/>
  <Item isSeparator="true"/>
  <Item Text="Mark Completed" ToggleOnMailMultiSelect="true" LabelN="Als afgewerkt markeren" LabelF="Marquer comme complété" ShowText="true" NavigateUrl="javascript:#GRID#.DoMailListAction(3,0);"/>
  <Item isSeparator="true"></Item>
  <Item Text="Mark Read" ShowText="true" LabelN="Markeren als gelezen" LabelF="Marquer comme lu" ToggleOnMailMultiSelect="true" NavigateUrl="javascript:#GRID#.DoMailBoxAction(6,0,1);"/>
  <Item Text="Mark UnRead" ShowText="true" LabelN="Markeren als ongelezen" LabelF="Marquer comme à lire" ToggleOnMailMultiSelect="true" NavigateUrl="javascript:#GRID#.DoMailBoxAction(7,0,1);"/>
  <Item isSeparator="true"/>
  <Item Text="Delete" LabelN="verwijderen" LabelF="Supprimer" LabelG="Löschen" ToggleOnMailMultiSelect="true" ImageClass="icon-delete" NavigateUrl="javascript:#GRID#.DoMailBoxAction(4,0,1);"/>
</Toolbar>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/CaseGridToolbar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">
<Item Text="Show Sidepanel" LabelN="Zijpaneel tonen" LabelF="Montrer le panneau latéral" ImageClass="icon-chevron-expand icon-color-light" NavigateUrl="javascript:#GRID#.ToggleShowSideBar();"/>
  <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraîchir" NavigateUrl="javascript:#GRID#.Reload();"/>


  <Item Text="What's new" ImageClass="icon-folder-mynewdocs" LabelE="" LabelN="Nieuwe items" LabelF="Quoi de neuf" NavigateUrl="javascript:#GRID#.ToggleWhatsNew();"/>

  <Item isSeparator="true"></Item>
<Item  Text="Start workflow" LabelE="Start workflow" LabelN="Workflow starten" LabelF="Démarrer workflow"  ImageClass="icon-case" ToggleOnMultiSelect="true" NavigateUrl="javascript:#GRID#.StartProcedureFromCaseSelection();"/>
  <Item Text="Create Object" LabelE="Create Object" LabelN="Object aanmaken" LabelF="Créer objet" ImageClass="icon-add-new" ToggleOnMultiSelect="true" NavigateUrl="javascript:#GRID#.CreateObjectFromCaseSelection();"/>
  <Item isSeparator="true"></Item>
  <Item Text="Print" LabelE="Print" LabelN="Afdrukken" LabelF="Imprimer" LabelG="Abdrucken" ImageClass="icon-printer"  NavigateUrl="javascript:#GRID#.PrintCaseGrid('CasePrintGrid.xml');"/>
  <Item Text="Export to Excel" LabelE="Export to Excel" LabelN="Exporteren naar Excel" LabelF="Exporter vers Excel" LabelG="Export to Excel" ImageClass="icon-filetype-excel"  NavigateUrl="javascript:#GRID#.PrintCaseGridToExcel('auto');"/>

  <Item Text="Download files to ZIP" ToggleOnMultiSelect="true" LabelE="" LabelN="Bestanden downloaden naar ZIP" LabelF="Télécharger les fichiers en ZIP" LabelG="" ImageClass="icon-download-zip" NavigateUrl="javascript:#GRID#.DoDocumentListAction(2,0);"/>

  <Item Text="Send by mail" ToggleOnMultiSelect="true" ImageClass="icon-message-mail-attach"  LabelE="" LabelN="Versturen per mail" LabelF="Envoyer par courriel" LabelG="" NavigateUrl="javascript:#GRID#.MailSelection();" />
  <Item Text="Compare Documents" ToggleOnMultiSelect="true" ImageClass="icon-document-compare" ShowText="false"  LabelE="" LabelN="Documenten vergelijken" LabelF="Comparer les documents" LabelG="" NavigateUrl="Javascript:PC().OpenWindow('./Tools/DocCompare.aspx?docs=' + #GRID#.GetSelection(),'compdocs');" />
  <Item Text="Compare Files" ToggleOnMultiSelect="true" ImageClass="icon-file-compare" ShowText="false" LabelE="" LabelN="Bestanden vergelijken" LabelF="Compares les fichiers" LabelG="" NavigateUrl="Javascript:PC().OpenWindow('./Tools/FileCompare.aspx?docs=' + #GRID#.GetSelection(),'compfiles');" />
  <Item isCustomActionPlaceHolder="true"></Item>

  <Item isSeparator="true"></Item>
<Item Text="Open workflows" LabelN="Workflows openen" LabelF="Ouvrir les workflows" ToggleOnCaseMultiSelect="true" ImageClass="icon-workflow-open" NavigateUrl="javascript:#GRID#.DoCaseListAction(8,0);"/>

  <Item Text="Unlock workflows" LabelN="Workflows ontgrendelen" LabelF="Déverrouiller les workflows" ToggleOnCaseMultiSelect="true" ImageClass="icon-lock-open" NavigateUrl="javascript:#GRID#.DoCaseListAction(2,0);"/>
  <Item Text="Release workflows" LabelN="Workflows vrijgeven" LabelF="Libérer les workflows" ToggleOnCaseMultiSelect="true" ImageClass="icon-action-release" NavigateUrl="javascript:#GRID#.DoCaseListAction(3,0);"/>

  <Item Text="Recalculate Work" LabelN="Werk herberekenen" LabelF="Récalculer le travail" ToggleOnCaseMultiSelect="true" ImageClass="icon-work-calc" NavigateUrl="javascript:#GRID#.DoCaseListAction(9,0);"/>


  <Item Text="Finish workflows" LabelN="Workflows beëindigen" LabelF="Terminer les workflows" RequiredFolderAcl="42" ToggleOnCaseMultiSelect="true" ImageClass="icon-action-finish" NavigateUrl="javascript:#GRID#.DoCaseListAction(6,0);"/>
  <Item Text="Delete workflows" LabelN="Workflows verwijderen" LabelF="Supprimer les workflows" RequiredFolderAcl="42" ToggleOnCaseMultiSelect="true" ImageClass="icon-delete"  NavigateUrl="javascript:#GRID#.DoCaseListAction(7,0);"/>


  <Item Text="Copy/Move to Folder" ToggleOnMultiSelect="true"  LabelE="Copy/Move/Shortcut to folder" ImageClass="icon-folder-moveto" LabelN="Kopieren/Verplaatsen/Snelkoppeling naar map" LabelF="Copier/Deplacer/Raccourci vers..." LabelG=""  NavigateUrl="javascript:#GRID#.CopyMoveSelection();" />

  <Item isSeparator="true"></Item>

  <Item Text="Add to Clipboard" ToggleOnMultiSelect="true" ImageClass="icon-copy-clipboard"  LabelE="" LabelN="Toevoegen aan het DocRoom Klembord" LabelF="Ajouter au Clipboard DocRoom" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(7);" />
  <Item Text="Add to favorites" ToggleOnMultiSelect="true" ImageClass="icon-favorites-add"  LabelE="" LabelN="Toevoegen aan de favorieten" LabelF="Ajouter aux favoris" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(3);" />
  <Item Text="Add to basket" ToggleOnMultiSelect="true" ImageClass="icon-basket-add"  LabelE="Add to your basket" LabelN="Toevoegen aan mand" LabelF="Ajouter au panier" LabelG="In den Korb legen" NavigateUrl="Javascript:#GRID#.AddToSelection(2);" /> 
</Toolbar>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/CDRomGridToolbar.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">
  <Item Text="Clear CD Rom List" LabelN="C rom lijst leegmaken" LabelF="Vider le CD" ImageUrl="ClearCD.png" NavigateUrl="javascript:#GRID#.ClearSelection(6,true);" />
  <Item Text="Remove from CD rom" ToggleOnMultiSelect="true" LabelN="Verwijderen uit de cd rom" LabelF="Supprimer du cd" ImageUrl="RemoveFromCD.png" NavigateUrl="javascript:#GRID#.RemoveFromSelection(6,true);" />
  <Item isSeparator="true"></Item>
  <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraîchir" NavigateUrl="javascript:#GRID#.Reload();"/>
  <Item Text="What's new" ImageClass="icon-folder-mynewdocs" ShowText="false" LabelE="" LabelF="Quoi de neuf" LabelN="Nieuwe items" LabelG="Neuigkeiten" NavigateUrl="javascript:#GRID#.ToggleWhatsNew();"/>
  <Item isSeparator="true"></Item>
  <Item Text="Print" LabelE="Print" LabelN="Afdrukken" LabelF="Imprimer" LabelG="Abdrucken" ImageClass="icon-printer"  NavigateUrl="javascript:#GRID#.PrintGrid();"/>
  <Item Text="Send by mail" ToggleOnMultiSelect="true" ImageClass="icon-message-mail-attach"  LabelE="Send by e-mail" LabelN="Versturen per mail" LabelF="Envoyer par courriel" LabelG="" NavigateUrl="javascript:#GRID#.MailSelection();" />
  <Item Text="Download to ZIP" ToggleOnMultiSelect="true" LabelE="" LabelN="Downloaden naar ZIP" LabelF="Télécharger en ZIP" LabelG="" ImageClass="icon-download-zip" NavigateUrl="javascript:#GRID#.DoDocumentListAction(2,0);"/>
  <Item Text="Compare Documents" ToggleOnMultiSelect="true" ImageClass="icon-document-compare" ShowText="false"  LabelE="" LabelN="Documenten vergelijken" LabelF="Comparer les documents" LabelG="" NavigateUrl="Javascript:PageController().OpenWindow('./Tools/DocCompare.aspx?docs=' + #GRID#.GetSelection(),'compdocs');" />
  <Item Text="Compare Files" ToggleOnMultiSelect="true" ImageClass="icon-file-compare" ShowText="false" LabelE="" LabelN="Bestanden vergelijken" LabelF="Comparer les fichiers" LabelG="" NavigateUrl="Javascript:PageController().OpenWindow('./Tools/FileCompare.aspx?docs=' + #GRID#.GetSelection(),'compfiles');" />
  <Item isCustomActionPlaceHolder="true"></Item>
  <Item isSeparator="true"></Item>
  <Item Text="Copy/Move to Folder" ToggleOnMultiSelect="true"  LabelE="Copy/Move/Shortcut to folder" ImageClass="icon-folder-moveto" LabelN="Kopieren/Verplaatsen/Shortcut naar map" LabelF="Copier/Deplacer/Raccourci vers..." LabelG=""  NavigateUrl="javascript:#GRID#.CopyMoveSelection();" />
  <Item Text="Delete" ToggleOnMultiSelect="true" LabelE="Delete" LabelN="Verwijderen" LabelF="Supprimer" LabelG="Löschen" ImageClass="icon-delete" NavigateUrl="javascript:#GRID#.DoDocumentListAction(4,0);"/>
  <Item isSeparator="true"></Item>
  <Item Text="Add to Clipboard" ToggleOnMultiSelect="true" ImageClass="icon-copy-clipboard"  LabelE="Add to Docroom Clipboard" LabelN="Toevoegen aan het DocRoom Klembord" LabelF="Ajouter au Clipboard" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(7);" />
  <Item Text="Add to favorites" ToggleOnMultiSelect="true" ImageClass="icon-favorites-add"  LabelE="Add to your favorites" LabelN="Toevoegen aan favorieten" LabelF="Ajouter aux favorites" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(3);" />
  <Item Text="Add to basket" ToggleOnMultiSelect="true" ImageClass="icon-basket-add"  LabelE="Add to your basket" LabelN="Toevoegen aan mand" LabelF="Ajouter au panier" LabelG="In den Korb legen" NavigateUrl="Javascript:#GRID#.AddToSelection(2);" />
</Toolbar>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/MailFollowUpToolbar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">
  <Item Text="Show Sidepanel" LabelN="Zijpaneel tonen" LabelF="Montrer le panneau latéral" ImageClass="icon-chevron-expand icon-color-light" NavigateUrl="javascript:#GRID#.ToggleShowSideBar();"/>
  
  <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraîchir" NavigateUrl="javascript:#GRID#.Reload();"/>

  <Item Text="What's new" ImageClass="icon-folder-mynewdocs" ShowText="false" LabelE="" LabelF="Quoi de neuf" LabelN="Nieuwe items" LabelG="Neuigkeiten" NavigateUrl="javascript:#GRID#.ToggleWhatsNew();"/>
  <Item isSeparator="true"/>
  <Item Text="Stop Follow-up" LabelN="Follow-up beëindigen" LabelF="Arrete le follow-up" ShowText="true" ToggleOnMailMultiSelect="true" NavigateUrl="javascript:#GRID#.DoMailListAction(4,0);"/>
  <Item isSeparator="true"/>
  <Item Text="Delete" LabelE="Delete" LabelN="Verwijderen" LabelF="Supprimer" LabelG="Löschen" ToggleOnMailMultiSelect="true" ImageClass="icon-delete" NavigateUrl="javascript:#GRID#.DoMailBoxAction(4,0,2);"/>

</Toolbar>

=== mohanarcoinfoindia/DomaWebPortal/Sites/Root/ListItemGridToolbar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Toolbar enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Xsd\GridToolbar.xsd">
<Item Text="Show Sidepanel" LabelN="Zijpaneel tonen" LabelF="Montrer le panneau latéral" ImageClass="icon-chevron-expand icon-color-light" NavigateUrl="javascript:#GRID#.ToggleShowSideBar();"/> 
 <Item Text="Refresh" ImageClass="icon-refresh" LabelN="Hernieuwen" LabelF="Rafraîchir" NavigateUrl="javascript:#GRID#.Reload();"/>
   
  <Item Text="What's new" ImageClass="icon-folder-mynewdocs" ShowText="false" LabelE="" LabelF="Quoi de neuf" LabelN="Nieuwe items" LabelG="Neuigkeiten" NavigateUrl="javascript:#GRID#.ToggleWhatsNew();"/> 
  <Item isSeparator="true"/>
  <Item Text="Add" LabelE="Add" LabelN="Toevoegen" LabelF="Ajouter" LabelG="Add" ImageClass="icon-add-new" NavigateUrl="javascript:#GRID#.AddNew();"/>

  <Item Text="Delete" ToggleOnMultiSelect="true" LabelE="Delete" LabelN="Verwijderen" LabelF="Supprimer" LabelG="Löschen" ImageClass="icon-delete" NavigateUrl="javascript:#GRID#.DoDocumentListAction(4,0);"/>
   <Item isSeparator="true"></Item>
  <Item Text="Print" LabelE="Print" LabelN="Afdrukken" LabelF="Imprimer" LabelG="Abdrucken" ImageClass="icon-printer"  NavigateUrl="javascript:#GRID#.PrintGrid();"/>
  <Item Text="Export to Excel" LabelE="Export to Excel" LabelN="Exporteren naar Excel" LabelF="Exporter vers Excel" LabelG="Export to Excel" ImageClass="icon-filetype-excel"  NavigateUrl="javascript:#GRID#.PrintGridToExcel('auto');"/>
 
  <Item isSeparator="true"></Item>
  <Item Text="Add to Clipboard" ToggleOnMultiSelect="true" ImageClass="icon-copy-clipboard"  LabelE="Add to Docroom Clipboard" LabelN="Toevoegen aan het DocRoom Klembord" LabelF="Ajouter au Clipboard" LabelG="" NavigateUrl="Javascript:#GRID#.AddToSelection(7);" />
</Toolbar>
